name: crdt_socket_sync
description: Conflict-free replicated data type (CRDT) - Socket sync implementation provided in dart
homepage: https://mattiapispisa.github.io/
repository: https://github.com/MattiaPispisa/crdt/tree/main/packages/crdt_socket_sync
topics: [crdt, socket, sync, fugue, hlc]

version: 0.3.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  crdt_lf: ^2.2.0
  hlc_dart: ^1.0.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  mocktail: 1.0.4
  test: ^1.24.0
